### ISSUE TITLE
Use `Cargo.lock`

### ISSUE THREAD

**Issue by tombh** [AnthonyTornetta/bevy_easy_compute#8]
This crate is currently broken because of deprecated function signatures in [pipeline_cache.rs](https://github.com/AnthonyTornetta/bevy_easy_compute/blob/7ea84533da90a648d0055bcb89c4529deb75b31c/src/pipeline_cache.rs). Eg errors like:
```
error[E0308]: mismatched types
   --> src/pipeline_cache.rs:418:63
    |
418 |                         let error_detail = err.emit_to_string(&self.shader_cache.composer);
    |                                                -------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `naga_oil::compose::Composer`, found `Composer`
    |                                                |
    |                                                arguments to this method are incorrect

```

[The Cargo Team actually now suggests committing `Cargo.lock` for libraries](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html). Apparently even if `Cargo.lock` ends up in a published crate manifest it's still not adhered to, the looser `Cargo.toml` versions are what are actually used for dependency graph solving.

But interestingly I don't think this would ever be a problem if this crate could remove that [pipeline_cache.rs](https://github.com/AnthonyTornetta/bevy_easy_compute/blob/7ea84533da90a648d0055bcb89c4529deb75b31c/src/pipeline_cache.rs) file. It's basically copied from the main Bevy codebase anyway, which means that even patch version bumps in Bevy run the risk of this crate going out of date. I've made [another issue](https://github.com/AnthonyTornetta/bevy_easy_compute/issues/7) about a possible approach that allows moving away from the `pipeline_cache.rs` file.

~~At least does anybody happen to have a copy of a working `Cargo.lock` file? I guess it would have been created if you tried the examples before `wgpu` and `naga` changed their function signatures.~~ Got it from #9

**Comment by AnthonyTornetta** [comment]
Resolved in #9 and #10 - Thanks!
